---
name: Check

# This workflow is triggered on pushes to any branch.
on: [push]

# Jobs run in parallel by default.
jobs:
  small-checks:
    name: Small Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: uchile-lint
        uses: ./lint/
